import { defineConfig } from 'astro/config';
import { integrations, markdown, vite } from './src/nimbus/astro-config.ts';

export default defineConfig({
  site: 'https://docs.longportwhale.com',
  srcDir: './src/nimbus',
  trailingSlash: 'never',
  build: {
    format: 'file',
  },
  redirects: {
    '/en/whalesdk/mobile-integration': '/en/whalesdk/whaleapp/overview',
    '/zh-cn/whalesdk/mobile-integration': '/zh-cn/whalesdk/whaleapp/overview',
    '/zh-hk/whalesdk/mobile-integration': '/zh-hk/whalesdk/whaleapp/overview',
    '/en/whalesdk/capabilities': '/en/whalesdk/whaleapp/capabilities',
    '/zh-cn/whalesdk/capabilities': '/zh-cn/whalesdk/whaleapp/capabilities',
    '/zh-hk/whalesdk/capabilities': '/zh-hk/whalesdk/whaleapp/capabilities',
    '/en/whalesdk/ios': '/en/whalesdk/whaleapp/ios',
    '/zh-cn/whalesdk/ios': '/zh-cn/whalesdk/whaleapp/ios',
    '/zh-hk/whalesdk/ios': '/zh-hk/whalesdk/whaleapp/ios',
    '/en/whalesdk/android': '/en/whalesdk/whaleapp/android',
    '/zh-cn/whalesdk/android': '/zh-cn/whalesdk/whaleapp/android',
    '/zh-hk/whalesdk/android': '/zh-hk/whalesdk/whaleapp/android',
    '/en/whalesdk/webtrade': '/en/whalesdk/whaleapp/web',
    '/zh-cn/whalesdk/webtrade': '/zh-cn/whalesdk/whaleapp/web',
    '/zh-hk/whalesdk/webtrade': '/zh-hk/whalesdk/whaleapp/web',
    '/en/whalesdk/optional-apis': '/en/whalesdk/whaleapp/optional-apis',
    '/zh-cn/whalesdk/optional-apis': '/zh-cn/whalesdk/whaleapp/optional-apis',
    '/zh-hk/whalesdk/optional-apis': '/zh-hk/whalesdk/whaleapp/optional-apis',
    '/en/whalesdk/technical-faq': '/en/whalesdk/whaleapp/technical-faq',
    '/zh-cn/whalesdk/technical-faq': '/zh-cn/whalesdk/whaleapp/technical-faq',
    '/zh-hk/whalesdk/technical-faq': '/zh-hk/whalesdk/whaleapp/technical-faq',
    '/en/whalesdk/core-overview': '/en/whalesdk/whalecore/overview',
    '/zh-cn/whalesdk/core-overview': '/zh-cn/whalesdk/whalecore/overview',
    '/zh-hk/whalesdk/core-overview': '/zh-hk/whalesdk/whalecore/overview',
    '/en/whalesdk/core-ios': '/en/whalesdk/whalecore/ios',
    '/zh-cn/whalesdk/core-ios': '/zh-cn/whalesdk/whalecore/ios',
    '/zh-hk/whalesdk/core-ios': '/zh-hk/whalesdk/whalecore/ios',
    '/en/whalesdk/core-android': '/en/whalesdk/whalecore/android',
    '/zh-cn/whalesdk/core-android': '/zh-cn/whalesdk/whalecore/android',
    '/zh-hk/whalesdk/core-android': '/zh-hk/whalesdk/whalecore/android',
  },
  markdown,
  integrations,
  vite,
});
