/*
 * x-value-source "获取可选值" button.
 *
 * Some request fields take their value from another endpoint's query result
 * (declared as `x-value-source` on the parameter in the OpenAPI spec).
 * Mintlify doesn't render unknown x-* fields and doesn't serve the spec
 * JSON at runtime, so the map below is embedded here (POC: hand-written;
 * production: generated by scripts/convert.py from the specs).
 *
 * For each mapped operation visible on the page, a button is appended to
 * the field row; clicking it opens a small form with the source endpoint's
 * optional request parameters (from its requestBody schema), queries it
 * (Bearer token asked once, kept in localStorage) and lists `value_field`
 * from `data.list[]` — click a value to copy it.
 */
(function () {
  var SERVER = "https://b-api.longbridge.xyz";
  var TOKEN_KEY = "whale-docs:value-source-token";

  // { "METHOD /path": { "<field name>": cfg } }
  // cfg.shape "refs": GET, no params, values from data.values[] (key/value/desc)
  // cfg.shape "list": query form from `params`, values from data.list[][value_field]
  // Generated by scripts/gen_value_sources.py from x-value-source annotations
  // in openapi.cn.json — do not edit by hand.
  // __VALUE_SOURCES_GENERATED_START__
  var VALUE_SOURCES = {
  "POST /v1/atm/va/add/withdraw/audit/rule": {
    "coin_quantity_list": {
      "endpoint": "GET /v1/datasets/refs/tenant_crypto_currencies",
      "shape": "refs"
    }
  },
  "POST /v1/atm/va/modify/withdraw/audit/rule": {
    "coin_quantity_list": {
      "endpoint": "GET /v1/datasets/refs/tenant_crypto_currencies",
      "shape": "refs"
    }
  },
  "POST /v1/atm/out/cash/package/rule": {
    "single_quota_currency_amount": {
      "endpoint": "GET /v1/datasets/refs/tenant_currencies_by_channel",
      "shape": "refs"
    },
    "support_region": {
      "endpoint": "GET /v1/datasets/refs/atm_out_cash_rule_region",
      "shape": "refs"
    },
    "rule_codes": {
      "endpoint": "GET /v1/datasets/refs/risk_rule_indicators_withdraw",
      "shape": "refs"
    }
  },
  "POST /withdraw/audit/create": {
    "region_codes": {
      "endpoint": "GET /v1/datasets/refs/cash_notice_bank_region",
      "shape": "refs"
    },
    "rule_codes": {
      "endpoint": "GET /v1/datasets/refs/risk_rule_indicators_finance_withdraw",
      "shape": "refs"
    },
    "currencies": {
      "endpoint": "GET /v1/datasets/refs/tenant_currencies_with_all",
      "shape": "refs"
    }
  },
  "POST /clearing/markets": {
    "market": {
      "endpoint": "GET /v1/datasets/refs/clearing_markets_all",
      "shape": "refs"
    },
    "custodian_id": {
      "endpoint": "GET /v1/datasets/refs/clearing_custodians",
      "shape": "refs"
    },
    "sub_position_no": {
      "endpoint": "GET /v1/datasets/refs/clear_sub_position_no_all",
      "shape": "refs"
    }
  },
  "POST /v2/ipo/rate/save": {
    "currency": {
      "endpoint": "GET /v1/datasets/refs/tenant_currencies_by_channel",
      "shape": "refs"
    }
  },
  "POST /forex/amount_config_add": {
    "currency": {
      "endpoint": "GET /v1/datasets/refs/global_currency_for_exchange",
      "shape": "refs"
    }
  },
  "POST /forex/amount_config_update": {
    "currency": {
      "endpoint": "GET /v1/datasets/refs/global_currency_for_exchange",
      "shape": "refs"
    }
  },
  "POST /atm/add/exchange/balance": {
    "params": {
      "endpoint": "GET /v1/datasets/refs/global_currency_for_exchange",
      "shape": "refs"
    }
  },
  "POST /billing/company_fee": {
    "custodian_id": {
      "endpoint": "GET /v1/datasets/refs/clear_custodian_broker_no_all",
      "shape": "refs"
    },
    "currency": {
      "endpoint": "GET /v1/datasets/refs/tenant_currencies_by_channel",
      "shape": "refs"
    }
  },
  "PUT /billing/company_fee": {
    "currency": {
      "endpoint": "GET /v1/datasets/refs/tenant_currencies_by_channel",
      "shape": "refs"
    }
  },
  "POST /billing/billing_item": {
    "biz_type": {
      "endpoint": "GET /v1/datasets/refs/billing_business_type_all",
      "shape": "refs"
    }
  },
  "POST /book/edit_booking_types": {
    "source_id": {
      "endpoint": "GET /v1/datasets/refs/book_data_source_editable",
      "shape": "refs"
    }
  },
  "POST /book/create_or_modify_account_entries_v2": {
    "source_id": {
      "endpoint": "GET /v1/datasets/refs/book_entry_data_source",
      "shape": "refs"
    },
    "payment_account_type_id": {
      "endpoint": "GET /v1/datasets/refs/pg_book_account_type_v2",
      "shape": "refs"
    },
    "payment_booking_type_id": {
      "endpoint": "GET /v1/datasets/refs/pg_book_types_pickid_v2",
      "shape": "refs"
    },
    "payment_business_group": {
      "endpoint": "GET /v1/datasets/refs/pg_book_business_group",
      "shape": "refs"
    },
    "payee_account_type_id": {
      "endpoint": "GET /v1/datasets/refs/pg_book_account_type_v2",
      "shape": "refs"
    },
    "payee_booking_type_id": {
      "endpoint": "GET /v1/datasets/refs/pg_book_types_pickid_v2",
      "shape": "refs"
    },
    "currency": {
      "endpoint": "GET /v1/datasets/refs/tenant_currencies_by_channel",
      "shape": "refs"
    },
    "org_id": {
      "endpoint": "GET /v1/datasets/refs/book_broker_show",
      "shape": "refs"
    },
    "bank_account": {
      "endpoint": "GET /v1/datasets/refs/book_bank_account",
      "shape": "refs"
    },
    "debit_feature": {
      "endpoint": "GET /v1/datasets/refs/pg_book_feature_all",
      "shape": "refs"
    },
    "credit_feature": {
      "endpoint": "GET /v1/datasets/refs/pg_book_feature_all",
      "shape": "refs"
    }
  },
  "POST /book/edit_account_merge_rule_v2": {
    "original_currency": {
      "endpoint": "GET /v1/datasets/refs/tenant_currencies_by_channel",
      "shape": "refs"
    },
    "convert_currency": {
      "endpoint": "GET /v1/datasets/refs/tenant_currencies_by_channel",
      "shape": "refs"
    }
  },
  "POST /book/data/check": {
    "sourceId": {
      "endpoint": "GET /v1/datasets/refs/book_data_source_editable",
      "shape": "refs"
    },
    "busi_type": {
      "endpoint": "GET /v1/datasets/refs/pg_book_types_bilateral_account",
      "shape": "refs"
    }
  },
  "POST /v1/risk_monitoring/rule_engine/save_risk_rule": {
    "group_id": {
      "endpoint": "GET /v1/datasets/refs/ref_client_group_query_risk",
      "shape": "refs"
    }
  },
  "POST /ut/order/admin/submit": {
    "fund_channel": {
      "endpoint": "GET /v1/datasets/refs/fund_channel",
      "shape": "refs"
    }
  },
  "POST /book/createAccountDetailsV2": {
    "sourceId": {
      "endpoint": "GET /v1/datasets/refs/book_source",
      "shape": "refs"
    },
    "bookingTypeId": {
      "endpoint": "GET /v1/datasets/refs/pg_book_types_pickid_v2",
      "shape": "refs"
    },
    "objectCode": {
      "endpoint": "GET /v1/datasets/refs/tenant_currencies_by_channel",
      "shape": "refs"
    }
  },
  "POST /book/account_detail/update": {
    "sourceId": {
      "endpoint": "GET /v1/datasets/refs/book_source",
      "shape": "refs"
    },
    "bookingTypeId": {
      "endpoint": "GET /v1/datasets/refs/pg_book_types_pickid_v2",
      "shape": "refs"
    },
    "objectCode": {
      "endpoint": "GET /v1/datasets/refs/tenant_currencies_by_channel",
      "shape": "refs"
    }
  },
  "POST /book/channelBillsModify": {
    "fundId": {
      "endpoint": "GET /v1/datasets/refs/fund_business_type",
      "shape": "refs"
    }
  },
  "POST /crs/generate_crs_file": {
    "batch": {
      "endpoint": "GET /v1/datasets/refs/crs_batch",
      "shape": "refs"
    }
  },
  "POST /atm/addRegion": {
    "name": {
      "endpoint": "GET /v1/datasets/refs/bank_country_code",
      "shape": "refs"
    }
  },
  "POST /atm/modifyRegion": {
    "name": {
      "endpoint": "GET /v1/datasets/refs/bank_country_code",
      "shape": "refs"
    }
  },
  "POST /forex/abnormal_apply": {
    "apply_channel_name": {
      "endpoint": "GET /v1/datasets/refs/forex_channel_api",
      "shape": "refs"
    }
  },
  "POST /atm/deposit/filter/rule": {
    "currency": {
      "endpoint": "GET /v1/datasets/refs/tenant_currencies_by_channel",
      "shape": "refs"
    },
    "business_type": {
      "endpoint": "GET /v1/datasets/refs/atm_bank_business_type",
      "shape": "refs"
    }
  },
  "POST /clearing/move_position": {
    "custodian_id": {
      "endpoint": "GET /v1/datasets/refs/clearing_custodians",
      "shape": "refs"
    },
    "sub_position_no": {
      "endpoint": "GET /v1/datasets/refs/clear_sub_position_no_all",
      "shape": "refs"
    }
  },
  "PUT /billing_tob/account_divide_commission_bo": {
    "package_id": {
      "endpoint": "GET /v1/datasets/refs/org_package_ref_org",
      "shape": "refs"
    }
  },
  "POST /admin/transfer/out/apply": {
    "params.stocks[].custodian": {
      "endpoint": "GET /v1/datasets/refs/clearing_custodians",
      "shape": "refs"
    },
    "params.stocks[].sub_position_no": {
      "endpoint": "GET /v1/datasets/refs/clear_sub_position_no_all",
      "shape": "refs"
    }
  },
  "POST /risk_event/settlement_frozen": {
    "currency": {
      "endpoint": "GET /v1/datasets/refs/tenant_currencies_by_channel",
      "shape": "refs"
    }
  },
  "POST /v1/portfolio/withdraw/by/admin": {
    "params.card_id": {
      "endpoint": "POST /v1/datasets/atm_withdraw_cards_effective",
      "shape": "list",
      "value_field": "id",
      "params": [
        {
          "key": "filters.member_id",
          "label": "客户"
        },
        {
          "key": "filters.account_type",
          "label": "币种"
        },
        {
          "key": "filters.account",
          "label": "银行账号"
        },
        {
          "key": "filters.region",
          "label": "银行账户地区"
        },
        {
          "key": "filters.bank_id",
          "label": "卡所属银行"
        },
        {
          "key": "filters.status",
          "label": "出金认证状态",
          "options": [
            {
              "value": "",
              "label": "全部"
            },
            {
              "value": "0",
              "label": "0 未认证"
            },
            {
              "value": "1",
              "label": "1 待认证"
            },
            {
              "value": "2",
              "label": "2 已认证"
            }
          ]
        },
        {
          "key": "page",
          "label": "页码",
          "placeholder": "1"
        },
        {
          "key": "page_size",
          "label": "每页数量",
          "placeholder": "20"
        }
      ],
      "base_body": {
        "filters": {},
        "page": 1,
        "page_size": 20,
        "orderBy": []
      },
      "label_fields": [
        "member_id",
        "region",
        "country"
      ]
    }
  },
  "POST /v1/risk_gateway/omnibus_cash_transfer": {
    "currency": {
      "endpoint": "GET /v1/datasets/refs/tenant_currencies_by_channel",
      "shape": "refs"
    }
  },
  "POST /v1/risk_monitoring/update_exchange_rule_v2": {
    "other": {
      "endpoint": "GET /v1/datasets/refs/global_currency_which_support_exchange",
      "shape": "refs"
    }
  }
};
  // __VALUE_SOURCES_GENERATED_END__

  function el(tag, style, text) {
    var n = document.createElement(tag);
    if (style) n.style.cssText = style;
    if (text) n.textContent = text;
    return n;
  }

  // The operation's path appears in the request example of the main content
  // area. Don't use document.body: it includes the Next.js route-data
  // <script> payloads, which mention every operation on the site.
  var pageText = "";
  function refreshPageText() {
    var main = document.getElementById("content-area") || document.querySelector("main");
    pageText = main ? main.textContent || "" : "";
  }
  function pageHasOperation(path) {
    return pageText.indexOf(path) !== -1;
  }

  // Param rows render the field name as a `div.font-semibold` whose exact
  // text is the field (e.g. "params.card_id"). Restricting to that shape
  // keeps us off identical-looking tokens inside code samples.
  function findFieldAnchor(field) {
    var nodes = document.querySelectorAll("div.font-semibold");
    for (var i = 0; i < nodes.length; i++) {
      var n = nodes[i];
      if (n.childElementCount === 0 && n.textContent.trim() === field && !n.closest("pre,code")) return n;
    }
    return null;
  }

  var inputStyle = "padding:4px 8px;border:1px solid #E4E4E7;border-radius:6px;font-size:12px;width:100%;box-sizing:border-box;background:transparent;";

  function setDeep(obj, dottedKey, value) {
    var keys = dottedKey.split(".");
    var cur = obj;
    for (var i = 0; i < keys.length - 1; i++) {
      if (typeof cur[keys[i]] !== "object" || cur[keys[i]] === null) cur[keys[i]] = {};
      cur = cur[keys[i]];
    }
    cur[keys[keys.length - 1]] = value;
  }

  // Query form: token row (until saved) + the source endpoint's optional
  // params + 查询 button. Results/errors render into `resultBox` below it.
  function buildPanel(container, cfg) {
    container.innerHTML = "";
    var form = el("div", "margin-top:6px;padding:10px;border:1px solid #E4E4E7;border-radius:8px;display:flex;flex-direction:column;gap:8px;");
    var resultBox = el("div", "");

    var tokenInput = null;
    if (!localStorage.getItem(TOKEN_KEY)) {
      tokenInput = el("input", inputStyle);
      tokenInput.type = "password";
      tokenInput.placeholder = "Bearer token (ACCESS_TOKEN)，将保存在本地";
      form.appendChild(tokenInput);
    }

    var grid = el("div", "display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:8px;");
    var fieldInputs = [];
    (cfg.params || []).forEach(function (p) {
      var wrap = el("label", "display:flex;flex-direction:column;gap:2px;font-size:11px;color:#71717A;");
      wrap.appendChild(el("span", "", p.label + "（" + p.key + "）"));
      var ctrl;
      if (p.options) {
        ctrl = el("select", inputStyle);
        p.options.forEach(function (o) {
          var opt = el("option", "", o.label);
          opt.value = o.value;
          ctrl.appendChild(opt);
        });
      } else {
        ctrl = el("input", inputStyle);
        ctrl.placeholder = p.placeholder || "可选";
      }
      wrap.appendChild(ctrl);
      grid.appendChild(wrap);
      fieldInputs.push({ key: p.key, ctrl: ctrl });
    });
    if (fieldInputs.length) form.appendChild(grid);

    var actions = el("div", "display:flex;gap:8px;align-items:center;");
    var run = el("button", btnStyle(), "查询");
    actions.appendChild(run);
    if (!tokenInput) {
      var reset = el("a", "font-size:12px;color:#7245F2;cursor:pointer;", "重设 Token");
      reset.onclick = function () {
        localStorage.removeItem(TOKEN_KEY);
        buildPanel(container, cfg);
      };
      actions.appendChild(reset);
    }
    form.appendChild(actions);
    container.appendChild(form);
    container.appendChild(resultBox);

    run.onclick = function () {
      if (tokenInput) {
        if (!tokenInput.value.trim()) { tokenInput.focus(); return; }
        localStorage.setItem(TOKEN_KEY, tokenInput.value.trim());
      }
      var body = JSON.parse(JSON.stringify(cfg.base_body || {}));
      fieldInputs.forEach(function (f) {
        var v = f.ctrl.value.trim();
        if (v !== "") setDeep(body, f.key, v);
      });
      runQuery(resultBox, container, cfg, body);
    };

    // Nothing to fill in (refs shape, token already saved) — query right away.
    if (!tokenInput && !fieldInputs.length) run.onclick();
  }

  function runQuery(resultBox, container, cfg, body) {
    resultBox.innerHTML = "";
    resultBox.appendChild(el("div", "font-size:12px;color:#71717A;margin-top:6px;", "加载中…"));
    var token = localStorage.getItem(TOKEN_KEY);
    var m = cfg.endpoint.split(" ");
    // The gateway sends no Access-Control-Allow-Origin, so a direct fetch is
    // CORS-blocked from any docs origin. Route through Mintlify's same-origin
    // playground proxy (the same endpoint Try It uses); it returns
    // { response: { status, data: <base64 body> } }.
    fetch("/_mintlify/api/request", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        method: m[0].toLowerCase(),
        url: SERVER + m[1],
        header: {
          authorization: "Bearer " + token,
          "content-type": "application/json",
        },
        body: body,
        cookie: {},
        query: {},
      }),
    })
      .then(function (r) { return r.json(); })
      .then(function (proxy) {
        var resp = proxy && proxy.response;
        var j = null;
        if (resp && resp.data) {
          var bytes = Uint8Array.from(atob(resp.data), function (c) { return c.charCodeAt(0); });
          j = JSON.parse(new TextDecoder().decode(bytes));
        }
        return { status: resp ? resp.status : 0, json: j };
      })
      .then(function (res) {
        resultBox.innerHTML = "";
        var j = res.json;
        if (res.status !== 200 || !j || j.code !== 0) {
          renderError(resultBox, container, cfg, "请求失败：HTTP " + res.status + (j && j.message ? " · " + j.message : ""));
          return;
        }
        var refs = cfg.shape === "refs";
        var list = (j.data && (refs ? j.data.values : j.data.list)) || [];
        if (!list.length) {
          resultBox.appendChild(el("div", "font-size:12px;color:#71717A;margin-top:6px;", "查询结果为空"));
          return;
        }
        var valueField = refs ? "key" : cfg.value_field;
        var box = el("div", "margin-top:6px;border:1px solid #E4E4E7;border-radius:8px;max-height:200px;overflow:auto;");
        list.forEach(function (item) {
          var v = item[valueField];
          var row = el("div", "display:flex;gap:10px;align-items:center;padding:5px 10px;font-size:12px;cursor:pointer;border-bottom:1px solid #F4F4F5;");
          row.appendChild(el("code", "color:#7245F2;font-weight:600;", v === undefined || v === null ? "—" : String(v)));
          var labelKeys = refs ? ["value", "desc"] : cfg.label_fields || [];
          var label = labelKeys.map(function (k) { return item[k]; }).filter(Boolean).join(" · ");
          row.appendChild(el("span", "color:#71717A;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;", label));
          row.title = "点击复制 " + valueField;
          row.onclick = function () {
            if (v === undefined || v === null) return;
            navigator.clipboard.writeText(String(v));
            row.style.background = "#F5F3FF";
            setTimeout(function () { row.style.background = ""; }, 400);
          };
          box.appendChild(row);
        });
        resultBox.appendChild(box);
      })
      .catch(function (e) {
        resultBox.innerHTML = "";
        renderError(resultBox, container, cfg, "请求失败：" + e.message);
      });
  }

  function renderError(resultBox, container, cfg, msg) {
    var row = el("div", "font-size:12px;color:#DC2626;margin-top:6px;display:flex;gap:10px;align-items:center;");
    row.appendChild(el("span", "", msg));
    var reset = el("a", "color:#7245F2;cursor:pointer;", "重设 Token");
    reset.onclick = function () {
      localStorage.removeItem(TOKEN_KEY);
      buildPanel(container, cfg);
    };
    row.appendChild(reset);
    resultBox.appendChild(row);
  }

  function btnStyle() {
    return "font-size:12px;padding:2px 10px;border:1px solid #7245F2;color:#7245F2;background:transparent;border-radius:9999px;cursor:pointer;line-height:18px;";
  }

  function inject(field, cfg) {
    var anchor = findFieldAnchor(field);
    if (!anchor || anchor.dataset.valueSourceDone) return;
    anchor.dataset.valueSourceDone = "1";
    var btn = el("button", btnStyle() + "margin-left:8px;vertical-align:middle;", "获取可选值");
    var panel = el("div", "");
    btn.onclick = function () {
      if (panel.childElementCount) { panel.innerHTML = ""; return; }
      buildPanel(panel, cfg);
    };
    anchor.parentElement.appendChild(btn);
    // Panel goes after the field-name row so the list renders full-width.
    var host = anchor.parentElement;
    host.parentElement.insertBefore(panel, host.nextSibling);
  }

  var scanQueued = false;
  function scan() {
    scanQueued = false;
    refreshPageText();
    Object.keys(VALUE_SOURCES).forEach(function (op) {
      var path = op.split(" ")[1];
      if (!pageHasOperation(path)) return;
      var fields = VALUE_SOURCES[op];
      Object.keys(fields).forEach(function (f) {
        inject(f, fields[f]);
      });
    });
  }

  new MutationObserver(function () {
    if (scanQueued) return;
    scanQueued = true;
    setTimeout(scan, 300);
  }).observe(document.documentElement, { childList: true, subtree: true });

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", scan);
  } else {
    scan();
  }
})();

/*
 * Sidebar `top` clamp.
 *
 * The mint theme's footer/sidebar scroll script sets inline
 * `top = headerOffset - (sidebarContentHeight - footerTop)` on #sidebar to
 * slide it up as the footer scrolls into view. On short pages the footer
 * is visible immediately and our sidebar content is thousands of pixels
 * tall, so it writes an absurd offset like `top:-1729px` (normal is
 * ~100px) and the top of the menu becomes unreachable.
 *
 * #sidebar is re-created on every SPA navigation, so the observer watches
 * the document subtree instead of one node — any style write on any
 * current or future #sidebar gets clamped to the navbar's bottom edge.
 */
(function () {
  function clamp(sidebar) {
    var navbar = document.getElementById("navbar");
    if (!sidebar || !navbar) return;
    var minTop = navbar.getBoundingClientRect().bottom;
    var top = parseFloat(sidebar.style.top);
    if (!isNaN(top) && top < minTop - 1) {
      sidebar.style.top = minTop + "px";
    }
  }

  new MutationObserver(function (muts) {
    for (var i = 0; i < muts.length; i++) {
      var t = muts[i].target;
      if (t && t.id === "sidebar") clamp(t);
    }
  }).observe(document.documentElement, {
    attributes: true,
    attributeFilter: ["style"],
    subtree: true,
  });

  // Also fix whatever value is already there at load.
  var s = document.getElementById("sidebar");
  if (s) clamp(s);
})();

/*
 * Language switcher: preserve api-reference path.
 *
 * Openapi-generated pages don't get proper sibling mapping across languages
 * on Mintlify cloud — clicking the language switcher on /cn/api-reference/xxx
 * falls back to /{targetLang}/introduction. Every language uses the same
 * operationId slug (from x-mint.href in the specs), so a plain URL rewrite
 * always works.
 *
 * The switcher items are `<div role="menuitem">` (not anchors) and clicks are
 * routed through Mintlify's own JS handler. We intercept the click in the
 * capture phase, and when the current URL is an api-reference page we
 * navigate to the same operationId under the picked language, stopping the
 * event so Mintlify's default (jump to /introduction) doesn't run.
 */
(function () {
  var LANG_BY_LABEL = {
    "English": "en",
    "简体中文": "cn",
    "繁體中文": "zh-Hant",
  };

  function currentApiRefSlug() {
    var m = location.pathname.match(/^\/(?:en|cn|zh-Hant|zh-hant)\/api-reference\/([^\/?#]+)$/i);
    return m ? m[1] : null;
  }

  document.addEventListener(
    "click",
    function (e) {
      var t = e.target;
      if (!t || !t.closest) return;
      var item = t.closest('[role="menuitem"][data-component-part="localization-select-item"]');
      if (!item) return;
      var lang = LANG_BY_LABEL[item.textContent.trim()];
      if (!lang) return;
      var slug = currentApiRefSlug();
      if (!slug) return;
      e.preventDefault();
      e.stopImmediatePropagation();
      location.href = "/" + lang + "/api-reference/" + slug;
    },
    true
  );
})();
