/*
 * x-value-source "获取可选值" button.
 *
 * Some request fields take their value from another endpoint's query result
 * (declared as `x-value-source` on the parameter in the OpenAPI spec).
 * Mintlify doesn't render unknown x-* fields and doesn't serve the spec
 * JSON at runtime, so the map below is embedded here (POC: hand-written;
 * production: generated by scripts/convert.py from the specs).
 *
 * For each mapped operation visible on the page, a button is appended to
 * the field row; clicking it opens a small form with the source endpoint's
 * optional request parameters (from its requestBody schema), queries it
 * (Bearer token asked once, kept in localStorage) and lists `value_field`
 * from `data.list[]` — click a value to copy it.
 */
(function () {
  var SERVER = "https://b-api.longbridge.xyz";
  var TOKEN_KEY = "whale-docs:value-source-token";

  // { "METHOD /path": { "<field name>": cfg } }
  // cfg.shape "refs": GET, no params, values from data.values[] (key/value/desc)
  // cfg.shape "list": query form from `params`, values from data.list[][value_field]
  // Generated by scripts/gen_value_sources.py from x-value-source annotations
  // in openapi.cn.json — do not edit by hand.
  // __VALUE_SOURCES_GENERATED_START__
  var VALUE_SOURCES = {};
  // __VALUE_SOURCES_GENERATED_END__

  function el(tag, style, text) {
    var n = document.createElement(tag);
    if (style) n.style.cssText = style;
    if (text) n.textContent = text;
    return n;
  }

  // The operation's path appears in the request example of the main content
  // area. Don't use document.body: it includes the Next.js route-data
  // <script> payloads, which mention every operation on the site.
  var pageText = "";
  function refreshPageText() {
    var main = document.getElementById("content-area") || document.querySelector("main");
    pageText = main ? main.textContent || "" : "";
  }
  function pageHasOperation(path) {
    return pageText.indexOf(path) !== -1;
  }

  // Param rows render the field name as a `div.font-semibold` whose exact
  // text is the field (e.g. "params.card_id"). Restricting to that shape
  // keeps us off identical-looking tokens inside code samples.
  function findFieldAnchor(field) {
    var nodes = document.querySelectorAll("div.font-semibold");
    for (var i = 0; i < nodes.length; i++) {
      var n = nodes[i];
      if (n.childElementCount === 0 && n.textContent.trim() === field && !n.closest("pre,code")) return n;
    }
    return null;
  }

  var inputStyle = "padding:4px 8px;border:1px solid #E4E4E7;border-radius:6px;font-size:12px;width:100%;box-sizing:border-box;background:transparent;";

  function setDeep(obj, dottedKey, value) {
    var keys = dottedKey.split(".");
    var cur = obj;
    for (var i = 0; i < keys.length - 1; i++) {
      if (typeof cur[keys[i]] !== "object" || cur[keys[i]] === null) cur[keys[i]] = {};
      cur = cur[keys[i]];
    }
    cur[keys[keys.length - 1]] = value;
  }

  // Query form: token row (until saved) + the source endpoint's optional
  // params + 查询 button. Results/errors render into `resultBox` below it.
  function buildPanel(container, cfg) {
    container.innerHTML = "";
    var form = el("div", "margin-top:6px;padding:10px;border:1px solid #E4E4E7;border-radius:8px;display:flex;flex-direction:column;gap:8px;");
    var resultBox = el("div", "");

    var tokenInput = null;
    if (!localStorage.getItem(TOKEN_KEY)) {
      tokenInput = el("input", inputStyle);
      tokenInput.type = "password";
      tokenInput.placeholder = "Bearer token (ACCESS_TOKEN)，将保存在本地";
      form.appendChild(tokenInput);
    }

    var grid = el("div", "display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:8px;");
    var fieldInputs = [];
    (cfg.params || []).forEach(function (p) {
      var wrap = el("label", "display:flex;flex-direction:column;gap:2px;font-size:11px;color:#71717A;");
      wrap.appendChild(el("span", "", p.label + "（" + p.key + "）"));
      var ctrl;
      if (p.options) {
        ctrl = el("select", inputStyle);
        p.options.forEach(function (o) {
          var opt = el("option", "", o.label);
          opt.value = o.value;
          ctrl.appendChild(opt);
        });
      } else {
        ctrl = el("input", inputStyle);
        ctrl.placeholder = p.placeholder || "可选";
      }
      wrap.appendChild(ctrl);
      grid.appendChild(wrap);
      fieldInputs.push({ key: p.key, ctrl: ctrl });
    });
    if (fieldInputs.length) form.appendChild(grid);

    var actions = el("div", "display:flex;gap:8px;align-items:center;");
    var run = el("button", btnStyle(), "查询");
    actions.appendChild(run);
    if (!tokenInput) {
      var reset = el("a", "font-size:12px;color:#7245F2;cursor:pointer;", "重设 Token");
      reset.onclick = function () {
        localStorage.removeItem(TOKEN_KEY);
        buildPanel(container, cfg);
      };
      actions.appendChild(reset);
    }
    form.appendChild(actions);
    container.appendChild(form);
    container.appendChild(resultBox);

    run.onclick = function () {
      if (tokenInput) {
        if (!tokenInput.value.trim()) { tokenInput.focus(); return; }
        localStorage.setItem(TOKEN_KEY, tokenInput.value.trim());
      }
      var body = JSON.parse(JSON.stringify(cfg.base_body || {}));
      fieldInputs.forEach(function (f) {
        var v = f.ctrl.value.trim();
        if (v !== "") setDeep(body, f.key, v);
      });
      runQuery(resultBox, container, cfg, body);
    };

    // Nothing to fill in (refs shape, token already saved) — query right away.
    if (!tokenInput && !fieldInputs.length) run.onclick();
  }

  function runQuery(resultBox, container, cfg, body) {
    resultBox.innerHTML = "";
    resultBox.appendChild(el("div", "font-size:12px;color:#71717A;margin-top:6px;", "加载中…"));
    var token = localStorage.getItem(TOKEN_KEY);
    var m = cfg.endpoint.split(" ");
    // The gateway sends no Access-Control-Allow-Origin, so a direct fetch is
    // CORS-blocked from any docs origin. Route through Mintlify's same-origin
    // playground proxy (the same endpoint Try It uses); it returns
    // { response: { status, data: <base64 body> } }.
    fetch("/_mintlify/api/request", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        method: m[0].toLowerCase(),
        url: SERVER + m[1],
        header: {
          authorization: "Bearer " + token,
          "content-type": "application/json",
        },
        body: body,
        cookie: {},
        query: {},
      }),
    })
      .then(function (r) { return r.json(); })
      .then(function (proxy) {
        var resp = proxy && proxy.response;
        var j = null;
        if (resp && resp.data) {
          var bytes = Uint8Array.from(atob(resp.data), function (c) { return c.charCodeAt(0); });
          j = JSON.parse(new TextDecoder().decode(bytes));
        }
        return { status: resp ? resp.status : 0, json: j };
      })
      .then(function (res) {
        resultBox.innerHTML = "";
        var j = res.json;
        if (res.status !== 200 || !j || j.code !== 0) {
          renderError(resultBox, container, cfg, "请求失败：HTTP " + res.status + (j && j.message ? " · " + j.message : ""));
          return;
        }
        var refs = cfg.shape === "refs";
        var list = (j.data && (refs ? j.data.values : j.data.list)) || [];
        if (!list.length) {
          resultBox.appendChild(el("div", "font-size:12px;color:#71717A;margin-top:6px;", "查询结果为空"));
          return;
        }
        var valueField = refs ? "key" : cfg.value_field;
        var box = el("div", "margin-top:6px;border:1px solid #E4E4E7;border-radius:8px;max-height:200px;overflow:auto;");
        list.forEach(function (item) {
          var v = item[valueField];
          var row = el("div", "display:flex;gap:10px;align-items:center;padding:5px 10px;font-size:12px;cursor:pointer;border-bottom:1px solid #F4F4F5;");
          row.appendChild(el("code", "color:#7245F2;font-weight:600;", v === undefined || v === null ? "—" : String(v)));
          var labelKeys = refs ? ["value", "desc"] : cfg.label_fields || [];
          var label = labelKeys.map(function (k) { return item[k]; }).filter(Boolean).join(" · ");
          row.appendChild(el("span", "color:#71717A;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;", label));
          row.title = "点击复制 " + valueField;
          row.onclick = function () {
            if (v === undefined || v === null) return;
            navigator.clipboard.writeText(String(v));
            row.style.background = "#F5F3FF";
            setTimeout(function () { row.style.background = ""; }, 400);
          };
          box.appendChild(row);
        });
        resultBox.appendChild(box);
      })
      .catch(function (e) {
        resultBox.innerHTML = "";
        renderError(resultBox, container, cfg, "请求失败：" + e.message);
      });
  }

  function renderError(resultBox, container, cfg, msg) {
    var row = el("div", "font-size:12px;color:#DC2626;margin-top:6px;display:flex;gap:10px;align-items:center;");
    row.appendChild(el("span", "", msg));
    var reset = el("a", "color:#7245F2;cursor:pointer;", "重设 Token");
    reset.onclick = function () {
      localStorage.removeItem(TOKEN_KEY);
      buildPanel(container, cfg);
    };
    row.appendChild(reset);
    resultBox.appendChild(row);
  }

  function btnStyle() {
    return "font-size:12px;padding:2px 10px;border:1px solid #7245F2;color:#7245F2;background:transparent;border-radius:9999px;cursor:pointer;line-height:18px;";
  }

  function inject(field, cfg) {
    var anchor = findFieldAnchor(field);
    if (!anchor || anchor.dataset.valueSourceDone) return;
    anchor.dataset.valueSourceDone = "1";
    var btn = el("button", btnStyle() + "margin-left:8px;vertical-align:middle;", "获取可选值");
    var panel = el("div", "");
    btn.onclick = function () {
      if (panel.childElementCount) { panel.innerHTML = ""; return; }
      buildPanel(panel, cfg);
    };
    anchor.parentElement.appendChild(btn);
    // Panel goes after the field-name row so the list renders full-width.
    var host = anchor.parentElement;
    host.parentElement.insertBefore(panel, host.nextSibling);
  }

  var scanQueued = false;
  function scan() {
    scanQueued = false;
    refreshPageText();
    Object.keys(VALUE_SOURCES).forEach(function (op) {
      var path = op.split(" ")[1];
      if (!pageHasOperation(path)) return;
      var fields = VALUE_SOURCES[op];
      Object.keys(fields).forEach(function (f) {
        inject(f, fields[f]);
      });
    });
  }

  new MutationObserver(function () {
    if (scanQueued) return;
    scanQueued = true;
    setTimeout(scan, 300);
  }).observe(document.documentElement, { childList: true, subtree: true });

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", scan);
  } else {
    scan();
  }
})();

/*
 * Sidebar `top` clamp.
 *
 * The mint theme's footer/sidebar scroll script sets inline
 * `top = headerOffset - (sidebarContentHeight - footerTop)` on #sidebar to
 * slide it up as the footer scrolls into view. On short pages the footer
 * is visible immediately and our sidebar content is thousands of pixels
 * tall, so it writes an absurd offset like `top:-1729px` (normal is
 * ~100px) and the top of the menu becomes unreachable.
 *
 * #sidebar is re-created on every SPA navigation, so the observer watches
 * the document subtree instead of one node — any style write on any
 * current or future #sidebar gets clamped to the navbar's bottom edge.
 */
(function () {
  function clamp(sidebar) {
    var navbar = document.getElementById("navbar");
    if (!sidebar || !navbar) return;
    var minTop = navbar.getBoundingClientRect().bottom;
    var top = parseFloat(sidebar.style.top);
    if (!isNaN(top) && top < minTop - 1) {
      sidebar.style.top = minTop + "px";
    }
  }

  new MutationObserver(function (muts) {
    for (var i = 0; i < muts.length; i++) {
      var t = muts[i].target;
      if (t && t.id === "sidebar") clamp(t);
    }
  }).observe(document.documentElement, {
    attributes: true,
    attributeFilter: ["style"],
    subtree: true,
  });

  // Also fix whatever value is already there at load.
  var s = document.getElementById("sidebar");
  if (s) clamp(s);
})();
