name: Update Pages
on:
  workflow_dispatch:
  schedule:
    # Every 3 days at 00:00
    - cron: "0 0 */3 * *"

jobs:
  export:
    name: Download feishu pages
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          branch: main

      - name: Use feishu pages cache
        uses: actions/cache@v3
        id: feishu_pages_export_cache
        with:
          path: ./feishu-pages/.cache
          key: feishu_pages_export_cache_key

      - name: Start export feishu pages
        env:
          FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
          FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
          FEISHU_SPACE_ID: "7288219896826494980"
          OUTPUT_DIR: ./feishu-pages
          URL_STYLE: original
          BASE_URL: ./
        uses: longbridgeapp/feishu-pages@main

      - uses: oven-sh/setup-bun@v1

      - name: Copy Pages to repo
        run: |
          bun install
          bun run setup

      - name: Commit feishu pages to repo
        run: |
          git checkout -b update-pages-$(date +'%Y-%m-%d')
          git status
          git add .
          git config --global user.name "Longbridge Whale docs bot"
          git config --global user.email "longbridge-whale-docs@users.noreply.github.com"
          git commit -a -m "Commit feishu updated pages to repo"
          git push origin update-pages-$(date +'%Y-%m-%d')

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update to export new feishu pages.
          base: main
          branch: update-pages-$(date +'%Y-%m-%d')
          title: "[Docs] New feishu pages version request review"
          body: |
            New feishu pages version request review
          assignees: ihavecoke
