name: Update Pages
on:
  workflow_dispatch:
  schedule:
    # Every 3 days at 00:00
    - cron: '0 0 */3 * *'
jobs:
  download_feishu_pages:
    name: Download feishu pages
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: feishu-pages

      - name: Use feishu pages cache
        uses: actions/cache@v3
        id: feishu_pages_export_cache
        with:
          path: ./feishu-pages/.cache
          key: feishu_pages_export_cache_key

      - name: Start export feishu pages
        env:
          FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
          FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
          FEISHU_SPACE_ID: "7288219896826494980"
          OUTPUT_DIR: ./feishu-pages
          URL_STYLE: original
          BASE_URL: ./
        uses: longbridgeapp/feishu-pages@main

      - uses: oven-sh/setup-bun@v1

      - name: Copy feishu pages to repo
        run: |
          bun install
          bun run setup

      - name: Commit feishu pages to repo
        run: |
          git status
          git add .
          git config --global user.name "feishu-pages-bot"
          git config --global user.email "longbridge-whale-docs@users.noreply.github.com"
          git commit -a -m "Update to export new feishu pages."

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update to export new feishu pages.
          base: dev
          branch: ${{github.ref_name}}
          title: "[UPDATE] Export Feishu Pages"
          body: |
            New feishu pages version request review
          assignees: ihavecoke
